### ISSUE TITLE
Confusion with the (+) signs

### ISSUE THREAD

**Issue by philipahn** [ga-dc/ga_exit_tickets#1]
Navigation is tricky. Not very apparent that the plus sign leads to:
1. adding a new lesson 
2. creating exit ticket form URL 
3. show pathway/directory of where user is at that given point
     - FEWD33 -> Intro to Javascript -> Exit tickets

**Comment by AndyWhitley** [comment]
I updated the `(+)` links to buttons consistent with the rest of the App. Will work on the breadcrumbs feature in time. Let me know if the buttons look better / easier to understand.

**Comment by AndyWhitley** [comment]
I added a "breadcrumbs" feature that keeps track of your navigation history (feature request #3 above). If it needs adjustment, feel free to reopen.
