### ISSUE TITLE
Aggregate exit ticket comments

### ISSUE THREAD

**Issue by philipahn** [ga-dc/ga_exit_tickets#2]
Survey responses should also show student comments. Difficult to see everything aggregrated if I have to click on individual student response:

**Comment by AndyWhitley** [comment]
Added a button to toggle the list of survey responses between showing summaries of ratings and comments. Check it out and let me know if this is what you were thinking.

**Comment by AndyWhitley** [comment]
Closing for now. Reopen if iterations needed.
