### ISSUE TITLE
Students can see other student responses if they delete "surveys" at the end of the url

### ISSUE THREAD

**Issue by philipahn** [ga-dc/ga_exit_tickets#3]
After deleting surveys from https://ga-exit-tickets.herokuapp.com/programs/1/lessons/3/surveys, all students can see what students wrote., 

<img width="723" alt="screen shot 2017-06-08 at 11 41 43 am" src="https://user-images.githubusercontent.com/17053208/26938137-5abfa2b8-4c41-11e7-8853-86cf269a9d56.png">

**Comment by AndyWhitley** [comment]
Fixed.
