### ISSUE TITLE
distribute red => green colors to make it more accurate with score range

### ISSUE THREAD

**Issue by philipahn** [ga-dc/ga_exit_tickets#4]
All numbers seem a little too green with conditional formatting of lesson metrics

1 should be red = #ffcccc
5 should be yellow = #ffffcc
10 should be green = #ccffcc

**Comment by AndyWhitley** [comment]
I just updated the coloration function to reduce the lightness of the color shading and to make them more distinguishable. Let me know how you feel about the new look.
