### ISSUE TITLE
paths

### ISSUE THREAD

**Issue by philipahn** [ga-dc/ga_exit_tickets#7]
Instructor from FEWD33 suggested this

<img width="526" alt="screen shot 2017-06-13 at 2 53 17 pm" src="https://user-images.githubusercontent.com/17053208/27099215-3b7dd18a-5048-11e7-9de3-3a6ba8f7f45e.png">

**Comment by AndyWhitley** [comment]
I changed all of the paths to use program names, lesson numbers, and query parameters to show student names.
